theme: jekyll-theme-minimal
title:  Digital Applications in Assyriology Nordic Summer School 2022
description: Training documents and materials for the DAA 2022, held at Uppsala University in Sweden 1-5 August
show_downloads: false
