theme: jekyll-theme-minimal
title:  Digital Applications in Assyriology (DAA) Nordic Summer School 2022
description: Description of the site
logo: logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
